const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Camiseta nike cuello redondo",
      price: 401,
      image: require('./images/Nike.png'),
      category: "Sueter",
      cantidad: 1,
      color: "blanco con azul"
    },
    {
      id: 2,
      title: "Blusa de mujer manga larga",
      price: 304,
      image: require('./images/blusa.png'),
      category: "Sueter mujer",
      img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-Pine-Green/Images/Nike-Dunk-Low-Off-White-Pine-Green/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606319825&w=1000",
      cantidad: 1,
      color: "gris oscuro"
    },
    {
      id: 3,
      title: "Sueter cuello redondo de deporte",
      price: 475,
      image: require('./images/pngwing.com (1).png'),
      category: "Sueter",
      cantidad: 1,
      color: "azul oscuro"
    },
    {
      id: 4,
      title: "chaqueta manga larga con capucha",
      price: 399,
      image: require('./images/pngwing.com (2).png'),
      category: "chaquetas",
      cantidad: 1,
      color: "negro"
    },
    {
      id: 5,
      title: "chaqueta manga larga con capucha",
      price: 405,
      image: require('./images/pngwing.com (3).png'),
      category: "chaquetas",
      cantidad: 1 ,
      color: "naranja"
    },
    {
      id: 6,
      title: "camisa tipo polo version smart ",
      price: 285,
      image: require('./images/pngwing.com (4).png'),
      category: "camisas",
      cantidad: 1 ,
      color: "verde smart" 
    } ,
    {
      id: 7,
      title: "camisa tipo polo version regular",
      price: 360,
      image: require('./images/pngwing.com (5).png'),
      category: "camisas",
      img1: "https://stockx-360.imgix.net/Nike-Air-Max-2-Light-Atmos/Images/Nike-Air-Max-2-Light-Atmos/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606320966&w=1000",
      cantidad: 1,
      color: "turquesa" 
    },
    {
      id: 8,
      title: "camisa tipo polo version courtly",
      price: 335,
      image: require('./images/pngwing.com (6).png'),
      category: "camisas",
      img1: "https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Clot-Blue-Silk/Images/Nike-Air-Force-1-Low-Clot-Blue-Silk/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325265&w=1000",
      cantidad: 1,
      color: "negro, gris y naranja"
    },
    {
      id: 9,
      title: "Camisa tipo polo version school",
      price: 799,
      image: require('./images/pngwing.com (7).png'),
      category: "camisas",
      img1: "https://stockx-360.imgix.net/Nike-Air-Max-90-OG-White-Particle-Grey-Volt/Images/Nike-Air-Max-90-OG-White-Particle-Grey-Volt/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606323250&w=1000",
      cantidad: 1, 
      color: "blanco"
    },
    {
      id: 10,
      title: "camisa manga larga version elegant",
      price: 501,
      image: require('./images/pngwing.com (8).png'),
      category: "camisas",
      img1: "https://stockx-360.imgix.net/Nike-Dunk-High-Black-Varsity-Maize/Images/Nike-Dunk-High-Black-Varsity-Maize/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609445259&w=1000",
      cantidad: 1,
      color: "gris claro"
    },
    {
      id: 11,
      title: "sueter cuello redondo version youthful",
      price: 377,
      image: require('./images/pngwing.com (9).png'),
      category: "sueter",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 1,
      color: "naranja"
    }, 
    {
      id: 12,
      title: "chaqueta manga larga con capucha version youthful",
      price: 377,
      image: require('./images/pngwing.com (10).png'),
      category: "sueter",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 30,
      color: "gris claro"
    },
    {
      id: 13,
      title: "sueter con magas cuello redondo version youthful",
      price: 377,
      image: require('./images/pngwing.com (11).png'),
      category: "sueter",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 23,
      color: "blanco con negro"
    },
    {
      id: 14,
      title: "jeans dril version standar",
      price: 377,
      image: require('./images/pngwing.com (12).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 145,
      color: "azul dril"
    },
    {
      id: 15,
      title: "jeans light cuello redondo version youthful",
      price: 377,
      image: require('./images/pngwing.com (13).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 45,
      color: "azul claro"
    },
    {
      id: 16,
      title: "jeans light mujer  version juvenile",
      price: 377,
      image: require('./images/pngwing.com (14).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 45,
      color: "azul claro"
    },
    {
      id: 17,
      title: "jeans light mujer  version childlike",
      price: 353,
      image: require('./images/pngwing.com (15).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 45,
      color: "azul claro"
    },
    {
      id: 18,
      title: "chaqueta hombre  version denim ",
      price: 353,
      image: require('./images/pngwing.com (18).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 45,
      color: "denim oscuro"
    },
    {
      id: 19,
      title: "short mujer  version young ",
      price: 353,
      image: require('./images/pngwing.com (16).png'),
      category: "short",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 45,
      color: "azul claro"
    },
    {
      id: 20,
      title: "jeans bota ancha  version standart ",
      price: 353,
      image: require('./images/pngwing.com (17).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 45,
      color: "azul dril"
    },
    {
      id: 21,
      title: "jeans hombre  version classic ",
      price: 353,
      image: require('./images/pngwing.com (19).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 15,
      color: "azul oscuro dril"
    },
    {
      id: 21,
      title: "jeans hombre  version young ",
      price: 353,
      image: require('./images/pngwing.com (20).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 15,
      color: "azul oscuro"
    },
    {
      id: 22,
      title: "jeans hombre  version junior ",
      price: 353,
      image: require('./images/pngwing.com (21).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 15,
      color: "azul oscuro mate"
    },
    {
      id: 23,
      title: " short mujer  version attractive ",
      price: 353,
      image: require('./images/pngwing.com (22).png'),
      category: "shorts",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "azul oscuro mate"
    },
    {
      id: 24,
      title: " jeans mujer  version classic ",
      price: 153,
      image: require('./images/pngwing.com (23).png'),
      category: "jeans",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "azul oscuro mate"
    },
    {
      id: 25,
      title: " vestido mujer  version attractive ",
      price: 153,
      image: require('./images/pngwing.com (25).png'),
      category: "vestidos",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 35,
      color: "naranja"
    },
    {
      id: 26,
      title: " vestido mujer  version trendy ",
      price: 153,
      image: require('./images/pngwing.com (26).png'),
      category: "vestidos",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "rojo"
    },
    {
      id: 27,
      title: " vestido mujer  version elegant ",
      price: 353,
      image: require('./images/pngwing.com (27).png'),
      category: "vestidos",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 25,
      color: "rojo "
    },
    {
      id: 28,
      title: " buzo mujer  version casual ",
      price: 153,
      image: require('./images/pngwing.com (28).png'),
      category: "buzos",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "rosado"
    }, 
    {
      id: 28,
      title: " sueter cuello redondo version sport ",
      price: 153,
      image: require('./images/pngwing.com (29).png'),
      category: "sueter",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "negro"
    },
    {
      id: 30,
      title: " buzo hombre  version casual ",
      price: 153,
      image: require('./images/pngwing.com (30).png'),
      category: "buzos",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "gris"
    },
    {
      id: 31,
      title: " sueter cuello redondo  version fitness ",
      price: 153,
      image: require('./images/pngwing.com (31).png'),
      category: "sueter",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "azul"
    },
    {
      id: 32,
      title: " sueter cuello redondo version youth ",
      price: 153,
      image: require('./images/pngwing.com (28).png'),
      category: "sueter",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "rosado"
    },
    {
      id: 33,
      title: " buzo mujer  version elegant ",
      price: 153,
      image: require('./images/pngwing.com (33).png'),
      category: "buzos",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "verde esmeralda"
    },
    {
      id: 34,
      title: " buzo hombre  version exotic",
      price: 153,
      image: require('./images/pngwing.com (34).png'),
      category: "buzos",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "rojo claro"
    },
    {
      id: 35,
      title: " camisa tipo polo hombre  version casual",
      price: 153,
      image: require('./images/pngwing.com.png'),
      category: "buzos",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 65,
      color: "rojo"
    },
  ],
};

export default data;